### ISSUE TITLE
cost points

### ISSUE THREAD

**Issue by keredson** [Nax/longflow-manifesto#7] opened 2016-12-19 14:43 UTC
I'm largely sympathetic to this.  (This is how we work at [HVST](https://www.hvst.com/) actually.)  Tho I would add in the concept of a cost point.  IE, if feature/bug `x` isn't live by date `y`, there will be `z` cost to the company.  (Lost customer, lost revenue, etc.)  They're an incredibly useful data point for prioritizing tasks, and should not be hidden from the developers if the developers are self-selecting tasks as you describe.

**Comment by Nax** [comment] 2016-12-19 15:03
I agree. The manifesto makes the following assumptions:

 * The developers show good will in their effort to improve the project.
 * The developers are competent at their job.

Under such assumptions, in the long term, the dev team will naturally converge towards efficiency. By comparing long term goals with actual issues, they will improve the product.

Not strictly related to your issue, but I think a lot of people read too much into the "No Estimates" part. This is my fault; I should have worded it differently. This does NOT mean "no priority" or "no communication", quite the opposite. That means the managers have no business tracking tasks at the implementation detail scale.

Back on tracks, I agree such a data point would be very useful. I am not sure the `x/y/z` system is optimal, but this is for sure something that will be added in version 2.

Anyway, thanks for your comment 👍

**Comment by anas-menuspring** [comment] 2016-12-19 15:46
I strongly believe in the idea you have given to the developers not only its concise but its too the point in nature from the very start , its self absorbing and is focused on how "efficiently" and transcendent in quality can achieve our goals no matter products or projects. 

I myself have worked with many companies for the last 8 or 9 years as programmer and I strongly believe that the rubbish of Agile and its various methodologies have now started affecting the true developers who are by nature innovative and want to take the products to next level no matter if they own it or not,
The very last such methodology following company I was working with , I was fired by that company just to re-assure them about the BS of Agile from time to time , but they never understood it and always went into miserable debts of the failure of various important aspects of their products and soon were acquired by another firm. 

Then I stopped getting myself hired into any such companies/software houses etc etc , finally landed into a company or rather I should say, I was being approached by a startup company named as MENUSPRING
http://www.eetapp.com/ from the very day first I now realise after reading the manifesto that they were following (this) kind of approach, the developer who was doing things before me was doing good but by the time I joined there were some major problems that the company was going through still at that crucial time they only asked me one thing that what could be done in the first place that there product could be saved rather than their company ? So I told them a few points and they left me with that asked me that now I am and will be the autocrat of the product - this is the point in time Nax that I realized that I was never an agile bullshit coder I was always enlightened by such methods but was never encouraged to go that way , but fate was with me atlast and with the help of Almighty Allah I was able to do things my way rather than any frigging petty methodology , I am not saying that Agile is nothing but we people who are working in this field must be confounded by the idea always that we have to do things and to solve problems by thinking over the nature of the problem rather than fitting that problem into a typical model.

My bosses are quite happy with me and let me tell you one surprising thing which might be eerie to some devs out there but its not like that believe me its not like that , I and my CTO hardly speak sometimes in a month or so and sometimes we speak every other day in a week but that is again something occasional I am not sugarcoating things but I'm telling and sharing that we do communicate with each-other but only when its really really important, as one of your points state this in manifesto, At the start it was startling me inside that we are not communicating like I used to communicate with my supervisors who were following the Agile model but over the passage of time I was amazed that I was performing way better , way efficient and way "accurately" with this approach that your manifesto , I envy you here ;) just kidding but this happened with me, but that said doesn't means that I am not achieving my tasks I do achieve them and sometimes before time and that's true ! not does this maintains a good will with your client but a very astonishing factor that I found following this manifesto is that it makes me that I am human let me elaborate it a little bit I have interviewed many of my peers who are always wearily behaving at their homes and in their families even on the weekends and in their spare times and the problem is always almost the similar that they are ominous about their tasks at work, I have been now working with this current employer of mine for the last 3 years and in those 3 years I have found myself intact in my personal and social life before it I was again one of my peers, I don't know and I have no notion if someone agrees to that point or not of mine but this does happens once you start.

I will try to spread your manifesto into my fellow mates and peers from ex-firms and I will try to make contributions to your manifesto from time to time. 

Thank you very much Nax for taking time to read my comments and thank you very very much for such a great effort of yours you have had converted into something that's really source of enlightenment for most of the frustrated devs out there, I wish you all the very best of luck with your work in future.

Best.

-Anas.

**Closed as completed** 2019-08-23 09:50 UTC
