### ISSUE TITLE
Not Business Oriented

### ISSUE THREAD

**Issue by alistra** [Nax/longflow-manifesto#4] opened 2016-12-19 08:26 UTC
I have a feeling that the manifesto doesn't take business and money into account - and IMO is not real world compatible.

It's a perfect way for the company to die because of lack of money. The king (Management) doesn't speak with the wizards in the Ivory Tower (engineers). The king may send a note and it may or may not be done in time, when the wizards decide it is time to do it between their arcane tasks.

This manifesto is making engineers overpowered in the organization, there ideally should be a balance between management and engineering. Engineering should work with management to work out long term goals and priorities. We don't always have time for the next refactor, because we may be bleeding customers because we need to change one if statement. Everything should be a dialog and everyone should be on the same page. Stop crying, that the person that pays you sometimes comes and wants to discuss things with you/wants you to do something.

**Comment by Nax** [comment] 2016-12-19 09:38
> It's a perfect way for the company to die because of lack of money.

If a company can die of lack of funds only because they implemented workflow X instead of Y, then there is a much bigger issue. Feedback should have been given, way, way before money starts to be a problem.

> The king (Management) doesn't speak with the wizards in the Ivory Tower (engineers).

You didn't read the manifesto. Managers speak with engineers. How do you want to manage without discussion? They just don't need to do so in formal, whole-team meetings. They can drop messages on Slack/Mattermost, or send emails, or comment on a tracker, whatever.

> The king may send a note and it may or may not be done in time, when the wizards decide it is time to do it between their arcane tasks.

Same as before. This is not what the manifesto is about. It's the job of the engineers to fix problems, implement features, etc. So tasks at the feature-level should be treated as implementation details and left to the guys dealing with the implementation. But the big picture is still directed by the managers.

 > This manifesto is making engineers overpowered in the organization.

No.

> There ideally should be a balance between management and engineering.

There is. See previous points.

> We don't always have time for the next refactor, because we may be bleeding customers because we need to change one if statement.

Since your team probably has at least 2 developers (or else it's not a team), you can probably do both.

> Stop crying, that the person that pays you sometimes comes and wants to discuss things with you/wants you to do something.

No issue with that. The issues starts when that person really want to talk to my coworker, but it still interrupts me somehow.

**Comment by FagnerMartinsBrack** [comment] 2016-12-19 12:14
> They can drop messages on Slack/Mattermost, or send emails, or comment on a tracker, whatever

Programmers are naturally egocentric and want to be seen as the best, it turns out we are just lucky in working in an industry with a low barrier to entry and high salary. Communication via e-mail, Slack and other tools work very well in Open Source Software because there is no way you can get in the same room with everyone to communicate clearly. Eric Raymonds also shows very well how Linux worked in [The Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) essay.

Science teaches us that humans have evolved and survived by using and improving social interactions. The reality is that most people won't have the same mindset necessary to make text communication work. People need personal communication to understand an idea clearly. [Pair Programming](https://medium.com/@fagnerbrack/pair-programming-8cfbf2dc4d00) and [Mob Programming](https://www.youtube.com/watch?v=8cy64qkgTyI) are much more efficient than a single dev working on a feature and they require verbal communication to reach maximum efficiency.

Dropping messages in tools that may or may not have reached the receiver won't have the same or more business benefit for a project than real communication. It's a matter of finding the best context for each. Both are essential.

> The issues starts when that person really want to talk to my coworker, but it still interrupts me somehow.

The problem is not the interruption by itself, but the context switch. Even in [when doing Pair Programming](https://hackernoon.com/how-to-do-pair-programming-wrong-dab72fd15bef) interruption is not a problem as long as both are in sync. If somebody start doing something differently or someone comes up with a task that is unrelated to the one you both are working, then the context switch drawbacks kicks in.

If the task is trivial and you are doing the work alone and somebody "interrupts" your colleague, there's something called noiseless headphone.

**Comment by connor4312** [comment] 2016-12-20 05:09
Speaking (my own views) as an employee of a recently-exited startup. I really love this manifest as an _engineer_--it's exactly my ideal world--but there are practical issues.

> If a company can die of lack of funds only because they implemented workflow X instead of Y, then there is a much bigger issue.

I very much disagree. Particularly for a startup, but even for a team working on a new product in an existing company, a workflow which ships 50% more product today is more likely to result in success, either by pulling in more traction before money runs out or before the project is killed.

> Since your team probably has at least 2 developers (or else it's not a team), you can probably do both.

See above. A team where one person is refactoring is shipping half the code today than one where both are working on new development. Yes yes, I know, linear versus logarithmic growth, I've been there, I've lobbied for more focus on maintainability and such in my company, but (to paraphrase an anecdote I read somewhere a while back) if you have amazing code and a crappy product, no one is going to want to use it, and it's going to die.

Personally, I love beautiful code, but at the end of the day I'm a product engineer who likes shipping awesome things that users want. As much as I love the idea of having no (or unimportant) deadlines, having self-assigned tasks, and so on and so forth, I believe that in most cases this is less likely to result in a successful business. If you're lucky enough to be part of a unicorn that prints money, sure, maybe you can shift your allocation of time and resources. But for the rest of us a more pragmatic balance between business and developer interests is necessary.

**Comment by anas-menuspring** [comment] 2016-12-20 06:32
Though I shared my experience in the other opened issue which is issue # 3 thought that better should share it here as well. Below is mine.

I strongly believe in the idea you have given to the developers not only its concise but its too the point in nature from the very start , its self absorbing and is focused on how "efficiently" and transcendent in quality can achieve our goals no matter products or projects.

I myself have worked with many companies for the last 8 or 9 years as programmer and I strongly believe that the rubbish of Agile and its various methodologies have now started affecting the true developers who are by nature innovative and want to take the products to next level no matter if they own it or not,
The very last such methodology following company I was working with , I was fired by that company just to re-assure them about the BS of Agile from time to time , but they never understood it and always went into miserable debts of the failure of various important aspects of their products and soon were acquired by another firm.

Then I stopped getting myself hired into any such companies/software houses etc etc , finally landed into a company or rather I should say, I was being approached by a startup company named as MENUSPRING
http://www.eetapp.com/ from the very day first I now realise after reading the manifesto that they were following (this) kind of approach, the developer who was doing things before me was doing good but by the time I joined there were some major problems that the company was going through still at that crucial time they only asked me one thing that what could be done in the first place that there product could be saved rather than their company ? So I told them a few points and they left me with that asked me that now I am and will be the autocrat of the product - this is the point in time Nax that I realized that I was never an agile bullshit coder I was always enlightened by such methods but was never encouraged to go that way , but fate was with me atlast and with the help of Almighty Allah I was able to do things my way rather than any frigging petty methodology , I am not saying that Agile is nothing but we people who are working in this field must be confounded by the idea always that we have to do things and to solve problems by thinking over the nature of the problem rather than fitting that problem into a typical model , and was able to make their product flourish again.

My bosses are quite happy with me and let me tell you one surprising thing which might be eerie to some devs out there but its not like that believe me its not like that , I and my CTO hardly speak sometimes in a month or so and sometimes we speak every other day in a week but that is again something occasional I am not sugarcoating things but I'm telling and sharing that we do communicate with each-other but only when its really really important, as one of your points state this in manifesto, At the start it was startling me inside that we are not communicating like I used to communicate with my supervisors who were following the Agile model but over the passage of time I was amazed that I was performing way better , way efficient and way "accurately" with this approach that your manifesto , I envy you here ;) just kidding but this happened with me, but that said doesn't means that I am not achieving my tasks I do achieve them and sometimes before time and that's true ! not does this maintains a good will with your client but a very astonishing factor that I found following this manifesto is that it makes me that I am human let me elaborate it a little bit I have interviewed many of my peers who are always wearily behaving at their homes and in their families even on the weekends and in their spare times and the problem is always almost the similar that they are ominous about their tasks at work, I have been now working with this current employer of mine for the last 3 years and in those 3 years I have found myself intact in my personal and social life before it I was again one of my peers, I don't know and I have no notion if someone agrees to that point or not of mine but this does happens once you start.

I will try to spread your manifesto into my fellow mates and peers from ex-firms and I will try to make contributions to your manifesto from time to time.

Thank you very much Nax for taking time to read my comments and thank you very very much for such a great effort of yours you have had converted into something that's really source of enlightenment for most of the frustrated devs out there, I wish you all the very best of luck with your work in future.

Best.

-Anas.

**Comment by akitaonrails** [comment] 2017-01-24 03:12
+1 it's not a novel idea and as before it lacks the basic economics. There is no infinite resources to spend. Assuming this models works, how do you justify the costs? Unless there is an objective way to measure, it's no better than wishful thinking. Unless the engineers are the stakeholders and investors themselves.

**Comment by Nax** [comment] 2017-01-24 08:25
> It's not a novel idea

Never said it was. It's not an idea, either, more like a collection of thoughts about software development, trying to fix issues with Scrum/Agile.

> It lacks the basic economics

No argumentation whatsoever.

> There is no infinite resources to spend.

Actually, as long as you make more money than you spend on everything else, there is.
I don't see your point, however. If you're not committed to spend a major part of your money on your product, you're probably already out of business.

> Assuming this models works, how do you justify the costs?

This question makes no sense.
If you assume the model works, then you also assume the claim (contained in the manifesto) that it is more time and cost effective. Have you read the manifesto?

> Unless there is an objective way to measure

To measure what? Cost? Time? Product quality?
They are ways to measure all of that, with varying degrees of precision.
By the same argument, I can also claim that Agile/Scrum/Whatever methodology you use is "wishful thinking", so your point is moot.

I also don't think you understand what wishful thinking is.

**Closed as completed** 2019-08-23 09:48 UTC
